Time to get started! 

Ok - time to take a break.  Go to a different room where you can't see or touch a single piece of the printer. Grab a refreshment, sit down and read through this all the way to the bottom. Once you have read all the way through it, and come back to this point, you can return to the printer. Remember, your camera is on and we can see if you don't do this!

First step is to get all of the heat sets placed.  If you are not familiar with this, Nero3D has a couple of good YouTube videos on it. 
https://youtube.com/shorts/cyof7fYFcuQ?feature=share


Start with the lower frame:

![Step1](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/ac8cb1ab-2427-40d4-b1e9-deb90d0f06e8)


Next Move on to the Bed Support

![IMG_0944](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/640278dc-e704-4322-8d72-15dd508da210)


Now the upper frame

![IMG_0945](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/503c44c5-9dc0-46db-a3d9-452808ec70ff)


...and the tool head parts

![IMG_0946](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/a4ef54b3-33e8-4f30-85fe-decae257661b)

Next up is attaching the feet to the legs. An M5 nut is captured in the leg and an M5 SHCS attaches the foot.

![IMG_0947](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/01f12731-5023-4249-940e-ea3da25681cb)


Attach all four feet to the lower frame as shown. 

![IMG_0948](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/866ceb6a-32cd-4668-9044-e205617f64af)


Stand it up, insert the 4 8mm rods into place. 

![IMG_0953](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/88638a28-65c9-48f6-9c29-1095ff2096da)

This is your firat "square and level check". On a known flat surface, make sure the feet don't wobble. Flip it to stand upside down and check for wobbles. This makes sure all the rods are inserted evenly. 

Grab the lower panel and the inserts. This should be a nice snug fit that can be tapped into place. Assemble all pieces. 


![IMG_0955](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/f4653d7a-c725-4ef4-98ea-43ab73e9f011)


Drop the panel down over the rods. Pay attention to orientation here. 

![IMG_0954](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/a2d6c7e6-98ad-4457-8248-84f978aa8e5b)


Insert the bearings into the bed support and center them. They are extra long on purpose to provide more support. Attach the Z endstop in place. 

![IMG_0956](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/da90a08e-81c1-499b-bff8-ad5152d4b642)

Lower the bed support onto the rear 8mm rods as shown. Note that the Z endstop faces down. 

![IMG_0957](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/20f56f12-3ac1-468a-9fe7-f37a9dc6e8f8)


Attach Y rails to the top frame. Leave the shuttle keepers in place for now. 

![IMG_0951](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/ccc64633-b06c-4294-935b-3a0cd30c6e39)


Place the top frame on top of the 8mm rods. Make sure it bottoms out on the rods. 

![IMG_0958](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/878a4ee0-0a65-4f05-817c-89a194e99c83)


Place motor mounts and front idlers on top frame. 
![IMG_0959](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/d99a324f-bc6f-404f-9a17-fb48b7716511)


Attach the linear rails to the X axis. Don't let the shuttle fall of the ends! 

![IMG_0961](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/a166939f-8148-4cfd-b01c-1cde7aa3a3bb)


Attach the X axis to the Y rails. 

![IMG_0960](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/38104176-597e-4258-bc6e-3dc1e3980fb6)

Attach the motors to the motor mounts, adjusted all the way towards the front of the printer.  Wires go towards the center. Attach the GT2 pulleys as shown. Pay attention to orientation and height. We will fine tune the height later.
![IMG_0966](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/0c402682-fca8-4f86-9c32-c2f2ac970fda)


This shows a proper bearing stack assembly for a double bearing stack.  Note the two shims in the middle. Always do shim-bearing-bearing-shim on a single. A double is two singles so two shims in the middle. 
![IMG_0963](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/660140b9-a612-4d0e-a748-9cb25ba517f0)

Install 4 single bearing stacks in the X axis. 

![IMG_0964](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/0dee16c5-1f56-4300-8029-b6c6ffe880d6)

![IMG_0965](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/f8d443ba-3c0e-4006-85e1-59f026c364cd)

...and a double bearing stack on each idler. 
![IMG_0967](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/76be85c5-bbfb-4f15-8b57-97c811e06880)

....and a single stack for the Z belt

![IMG_0998](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/9c9256b9-bec2-402a-9d33-c7f08331c0af)



The belt path is a standard CoreXY belt path. Study the two pics carefully. One is a cut away and the other is a normal view.  Being methodical here will pay off in the long run. 

![IMG_0971](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/539ab719-bbdf-4ab1-9f65-b173fa277d98)


![IMG_0970](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/16272b4e-b2f0-4010-b70d-91ee5ad0601a)

The first step will use the full length of the supplied belt. With the teeth facing front, insert one end of the belt through the back of the mounting plate throught the top, right side yellow hole of the blue part in the picture. Fold the belt back over itself so about 25mm overlaps, teeth to teeth. Use a wire tie to temporarily secure it. (Note: my CAD skills and time did not allow me to show the belt loop or teeth so follow the words, not just the picture) 
![IMG_0969](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/47f429df-d14d-4f19-bb7a-6af6817d3ee5)


Using tne picture above, route the other end through the top belt path all the way around and back through the top left hole from behind. Pull snug and temporarily secure the belt back onto itself. 

Carefully review your work while looking at the belt path in the picture. Make sure the belt is riding properly on each beating. 

Cut the belt about 25mm past the securing point. (So you have an extra 25mm). 

Now completely remove the belt.  

Lay the piece you just cut on top of the remaining belt and align the ends. The goal is to cut another piece the exact same length, down to the number of teeth.  Doing this right will make tuning easier later on.

Insert each belt through the back of the tool head mount (blue part) from the back on the same side, one top and one bottom. Fold each one back on itself, teeth to teeth, just enough to secure them together. (About 25mm). Do this identical for each one, down to the tooth. Secure each one to itself with two wire ties.

Loosely attach the tool head moint to the X rail.  Now reroute each belt according the the photos. Push the ends through the back of the tool head mount (might be easier to remove the mount from the tail for a minute) and pull tight. Ensure rhe same amount of teeth are exposed on each belt. When pulling, pull across the rail and not towards the front as that may break the part. Secure the belts back on to themselves and the mount to the rail. We will tighten later with the A and B motors. Paying attention to cutting the belts the same length, securing them the same, routing the properly and securing thr opposite end the same length will help a great deal in initial tuning later.

Next, mount the Rookery Hotend to it's mount through the top two holes. 

![IMG_1001](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/0bb67211-46f6-40a4-946d-37eb09f364eb)

Place this assembly onto the X carriage and secure it from the back through the bottom hole. 
![IMG_1003](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/7fcfceb4-5116-49b1-adfb-fb0f43eb71c0)

![IMG_1002](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/ffcad809-15f7-427d-b3d8-29a3d3b0131d)

Place the 4010 fans into the shroud. Start by routing wires in first and through the access holes in the center. Outflow gors down, inflow faces out. 

![IMG_1004](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/422eabd7-758d-42db-8541-3eb75af457bc)


Attach this assembly to the carriage and add the stress relief wire mount. 

![IMG_1005](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/922f2b95-6ca6-4101-98ff-474264e45ce7)

Install the Z motor and pulley as shown. The motor should be shifted as far towards the top of the printer as possible. m
![IMG_1007](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/26c38f59-b362-43a6-b1f0-4e9a43f7a1ea)

Install the Z belt as shown. Use the same process as A/B belts to fasten the belt back on itself. See the cut-away view on how to route eaxh end. Wrap one end around the bed support and secure it back on itself with two wires ties, route as shown all the way around back through the other partion of the bed support. Pull tight and secure it to itself, cut off excess. 

![IMG_1011](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/cc4003ef-b1f1-4362-9f70-fbbbeff29f38)

![IMG_1010](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/eacf75ec-54c5-4db7-87af-e786ef180b02)

![IMG_1009](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/79dbcc4f-4bab-48ef-a1fb-246c009f72dd)

![IMG_1008](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/99d165ec-4610-4128-bf79-bd7c5643410f)
