# Rook MK1 By Rolohaun 3D
---
### Time to get started! 

Ok - time to take a break.  Go to a different room where you can't see or touch a single piece of the printer. Grab a refreshment, sit down and read through this all the way to the bottom. Once you have read all the way through it, and come back to this point, you can return to the printer. Remember, your camera is on and we can see if you don't do this!

First step is to get all of the heat sets placed. There are 2 different sized heatsets in the kit. Its important to use the shorter heatsets on the rookery and mounting key. If you are not familiar with this, Nero3D has a couple of good YouTube videos on it. 
https://youtube.com/shorts/cyof7fYFcuQ?feature=share


 ### Start by placing heatsets into the lower frame:

![Step1](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/ac8cb1ab-2427-40d4-b1e9-deb90d0f06e8)


 ### Then place them into the Bed Support, dont forget to place them in the thumbscrews as well (not pictured)

![IMG_0944](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/640278dc-e704-4322-8d72-15dd508da210)


 ### Next, the upper frame

![IMG_1032](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/bae4c77e-a20b-4656-ac81-389fe379a789)


 ### ...and finally, the tool head parts

![IMG_0946](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/a4ef54b3-33e8-4f30-85fe-decae257661b)

 ### Next up is attaching the feet to the legs. 
 An M5 nut is captured in the leg and 4 M5X16 SHCS attach the feet.

![IMG_0947](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/01f12731-5023-4249-940e-ea3da25681cb)


 ### Attach all four feet to the lower frame as shown using 8 M3x10 SHCS. 

![IMG_0948](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/866ceb6a-32cd-4668-9044-e205617f64af)


 ### Stand the printer up and insert the four 8mm rods into place. 

![IMG_0953](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/88638a28-65c9-48f6-9c29-1095ff2096da)

 ### This is your first "square and level check". 
 On a known flat surface, make sure the feet don't wobble. Flip it to stand upside down and check for wobbles. This makes sure all the rods are inserted evenly. 
 Grab the lower panel and the inserts. This should be a nice snug fit that can be tapped into place. Assemble all pieces. 


![IMG_0955](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/f4653d7a-c725-4ef4-98ea-43ab73e9f011)


 ### Drop the panel down over the rods. 
 Pay attention to orientation here. 

![IMG_0954](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/a2d6c7e6-98ad-4457-8248-84f978aa8e5b)


 ### Insert the bearings into the bed support and center them. 
 They are extra long on purpose to provide more support. Attach the Z endstop in place using two M3x6 SHCS. 

![IMG_0956](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/da90a08e-81c1-499b-bff8-ad5152d4b642)

 ### Lower the bed support onto the rear 8mm rods as shown. Note that the Z endstop faces down. 

![IMG_0957](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/20f56f12-3ac1-468a-9fe7-f37a9dc6e8f8)


 ### Attach Y rails to the top frame with 16 M3x20 SHCS. 
 Leave the shuttle keepers in place for now.

![IMG_0951](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/ccc64633-b06c-4294-935b-3a0cd30c6e39)


 ### Place the top frame on top of the 8mm rods. 
 Make sure it bottoms out on the rods.

![IMG_0958](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/878a4ee0-0a65-4f05-817c-89a194e99c83)


 ### Place motor mounts and front idlers on top frame. 
 Two M3x16 BHCS (one each) go in the idlers from the front.  Two M3x10 (one each) attach them from the sides. Two M3X8 SHCS (one each) attach the motor mount from the side into the plastic (be careful not to overtighten/strip these). Two M3x18 SHCS (one each) attach the mount from the rear. 
![IMG_0959](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/d99a324f-bc6f-404f-9a17-fb48b7716511)


 ### Attach the linear rail to the X axis.
 Attach the rail to the x-axis using eight M3X12 BHCS with a washer and M3 nut on the back of each. Don't let the shuttle fall of the ends! 

![IMG_0961](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/a166939f-8148-4cfd-b01c-1cde7aa3a3bb)


 ### Attach the X axis to the Y rails.
 Attach using three M3x6 SHCS on each side (six total). 

![IMG_0960](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/38104176-597e-4258-bc6e-3dc1e3980fb6)

 ### Attach the A/B motors
 Attach the motors to the motor mounts with four M3x10 SHCS (eight total), adjusted all the way towards the front of the printer.  Wires go towards the center. Attach the GT2 pulleys as shown. Pay attention to orientation and height. We will fine tune the height later.
![IMG_0966](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/0c402682-fca8-4f86-9c32-c2f2ac970fda)


 ### This shows a proper bearing stack assembly for a double bearing stack.  
 Note the two shims in the middle. Always do shim-bearing-bearing-shim on a single. A double is two singles so two shims in the middle. 
![IMG_0963](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/660140b9-a612-4d0e-a748-9cb25ba517f0)

 ### Install four single bearing stacks in the X axis using M5x25 SHCS. 

![IMG_0964](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/0dee16c5-1f56-4300-8029-b6c6ffe880d6)

![IMG_0965](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/f8d443ba-3c0e-4006-85e1-59f026c364cd)

 ### ...and a double bearing stack on each idler using M5x30 SHCS. 
![IMG_0967](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/76be85c5-bbfb-4f15-8b57-97c811e06880)

 ### ...and a single stack for the Z belt using an M5x20 SHCS.

![IMG_0998](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/9c9256b9-bec2-402a-9d33-c7f08331c0af)


 ### The belt path is a standard CoreXY belt path. Study the two pics carefully. One is a cut away and the other is a normal view.  Being methodical here will pay off in the long run. 

![IMG_0971](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/539ab719-bbdf-4ab1-9f65-b173fa277d98)


![IMG_0970](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/16272b4e-b2f0-4010-b70d-91ee5ad0601a)

 ### Install the Belt Clamp
We will be taking the mount on and off a couple times. It attaches using 4 M3x6 BHCS. The first step will use the full length of the supplied belt. With the teeth facing front, insert one end of the belt through the back of the mounting plate throught the top, right side yellow hole of the blue part in the picture. Fold the belt back over itself so about 25mm overlaps, teeth to teeth. Use a wire tie to temporarily secure it. (Note: my CAD skills and time did not allow me to show the belt loop or teeth so follow the words, not just the picture) 
![IMG_0969](https://github.com/FHOGPHIL/Rook_Fabreeko/assets/69829255/47f429df-d14d-4f19-bb7a-6af6817d3ee5)


-  Using the picture above, route the other end through the top belt path all the way around and back through the top left hole from behind.
  - Pull snug and temporarily secure the belt back onto itself.
  - Carefully review your work while looking at the belt path in the picture. Make sure the belt is riding properly on each beating. 

- Cut the belt about 25mm past the securing point. (So you have an extra 25mm). 

- Completely remove the belt.  
  - Lay the piece you just cut on top of the remaining belt and align the ends. The goal is to cut another piece the exact same length, down to the number of teeth. **Making sure there are the same amount of teeth in each belt is vital to print quality**

- Insert each belt through the back of the tool head mount (blue part) from the back on the same side, one top and one bottom.
- Fold each one back on itself, teeth to teeth, just enough to secure them together. (About 25mm). Do this identical for each one, **down to the tooth**. Secure each one to itself with two zip ties.

Loosely attach the tool head mount to the X rail.  Now reroute each belt according the the photos. Push the ends through the back of the tool head mount (might be easier to remove the mount for a minute) and pull tight. Ensure the same amount of teeth are exposed on each belt.  When pulling, pull across the rail and not towards the front as that may break the part. Secure the belts back on to themselves and the mount to the rail. We will tighten later with the A and B motors. Paying attention to cutting the belts the same length, securing them the same, routing them properly and securing the opposite end the same length will help a great deal in initial tuning later. Note that the hotend key is designed such that the belts wont be tight enough to grab the key holes without sliding out. They rely on the friction of the mesh when you fold the belts back onto themselves and secure with a zip-tie.

### Next, mount the Rookery Hotend 
Mount the hotend and secure it to it's mount through the top two holes two M3x16 SHCS. 

![IMG_1001](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/0bb67211-46f6-40a4-946d-37eb09f364eb)

### Place this assembly onto the X carriage
Secure it from the back through the bottom hole with one M3X8 BHCS. 
![IMG_1003](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/7fcfceb4-5116-49b1-adfb-fb0f43eb71c0)

![IMG_1002](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/ffcad809-15f7-427d-b3d8-29a3d3b0131d)

### Place the 4010 fans into the shroud.
Start by routing wires in first and through the access holes in the center. Outflow goes down, inflow faces out. Mount the 3010 fan in place with 4 M3x16 BHCS, washers and M3 nuts.
![IMG_1004](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/422eabd7-758d-42db-8541-3eb75af457bc)


### Attach Rookery assembly to the carriage
- Mount the entire hotend shroud to the printer by sliding it into place, and secure with 2 M3x6 BHCS. Then and add the stress relief wire mount with 2 more M3x6 BHCS. 
- You may notice there is a wire managemnt tab on your hotend that is getting in the way of the rookery. You can (and should) rotate this to the front of the machine, and route the wires between the fan and the heatsink. You can rotate this by losening the set screw on the front of the hot end.

![IMG_1005](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/922f2b95-6ca6-4101-98ff-474264e45ce7)

### Install the Z motor and pulley as shown using 4 M3x12 BHCS. 
The motor should be shifted as far towards the top of the printer as possible to allow for adjustment later.
![IMG_1007](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/26c38f59-b362-43a6-b1f0-4e9a43f7a1ea)

### Install the Z belt as shown. 
- Use the same process as A/B belts to fasten the belt back on itself.
  - See the cut-away view on how to route each end. 
- Wrap one end around the bed support and secure it back on itself with two zip ties, route as shown all the way around back through the other portion of the bed support.
- Pull tight and secure it to itself, cut off excess. 

![IMG_1011](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/cc4003ef-b1f1-4362-9f70-fbbbeff29f38)

![IMG_1010](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/eacf75ec-54c5-4db7-87af-e786ef180b02)

![IMG_1009](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/79dbcc4f-4bab-48ef-a1fb-246c009f72dd)

![IMG_1008](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/99d165ec-4610-4128-bf79-bd7c5643410f)

### Install the MCU, Fan and (if using this solution) the RPi Zero 2.

![IMG_1016](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/b07ce6e3-3e2c-42b4-859e-b5e518504b21)

### Attach the Z Endstop using M2.5x12 self tapping screws
![IMG_1017](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/0a27df08-164a-4060-87c1-8dfe09010d3d)

### Attach screws to Bed
- Attach three m3x50mm SHCSs to the bed by sliding the screw through the hole in the top
- Secure the screws to the bed using an M3 washer and nut on the under side of the bed.
### Attach Bed to Frame
- Slide included yellow bed springs over the screws
- Secure the bed to the bed mount using the three thumbscrews we printed.
- Finally, Install the thermistor in the bed, it screws into the hole in the bottom center.

### Push the power port in place.
![IMG_1019](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/52d70599-2527-4801-b18d-4c52d1aec564)

### Attach the skirts
The skirts will be the last printed parts to attach. Leave them off for now, but this shows where they go. You will need to do all of the wiring first. The area highlighted in green are wire tie paths for small wire ties to help with wire management as you finish up. 
![IMG_1020](https://github.com/Fabreeko/Rook_Fabreeko/assets/69829255/242a2e47-c763-4a1f-8f7a-d5fc2c2ea6af)

### Attach the PSU
We suggest getting all the startup checks and tuning with the PSU sitting next to the printer until you are fairly certain that all is well. When you are all set, add the skirts and finally the PSU. The PSU mounts through the holes in the front feet, and will sit "below" your previously installed electronics.

### Wiring
- The wiring process is tedious for sure, but also straight forward, especally if you have previously built a printer.
- Use the MCUs github and follow the printer.cfg here to place all the wires correctly. 
- If you have not done wiring for a printer before, watching a couple of videos on YouTube may help. 

### Mini Sherpa Extruder
- The last thing for you to do is to build the extruder. The Extruder we are using is the mini sherpa. Please use the files in this repo, as the stock mini sherpa **does not work/properly mount with our bowden setup.** That said, the build process should be the same, and can be found in here. https://github.com/Annex-Engineering/Sherpa_Mini-Extruder/tree/master/Build_Instructions
  
- Note that some kits ship with a gear that is too long.
  - If, when assembling, you notice that the filament path in the print cannot line up with the one on the gear, its because the plastic spacing on the base of the white gear is too long. You may need to widdle this down by ~1mm (photos and fix credit Kwisatz_Nine9 on discord)

![IMG_2425](https://github.com/Fabreeko/Rook/assets/10854970/b1a10bf4-920b-413d-baab-4f5c040f28a3)
![IMG_2424](https://github.com/Fabreeko/Rook/assets/10854970/ea0be04e-45e6-4051-839f-e0131790d927) 

After building the mini-sherpa, mount it to the back of the machine and run a bowden tube between the extruder and the hot end.

